export const LOAD_SERVICES_LIST = 'LOAD_SERVICES_LIST';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_DESCRIPTION = 'LOAD_DESCRIPTION';
export const LOAD_DESCRIPTION_SUCCESS = 'LOAD_DESCRIPTION_SUCCESS';